version: '3'
services:
  mysql-master:
    container_name: mysql-master
    image: mysql:5.7
    environment:
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - "33306:3306"
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --server-id=11 --log-bin=mysql-bin
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
      - ./master/data:/var/lib/mysql
      - ./localtime:/etc/localtime
      - ./timezone:/etc/timezone
    restart: always
    networks:
      - overlay
  mysql-slave:
    container_name: "mysql-slave"
    image: mysql:5.7
    environment:
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    depends_on:
      - mysql-master
    ports:
      - "33307:3306"
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --server-id=21 --log-bin=mysql-bin --relay_log=mysql-relay-bin  --read_only=1
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
      - ./slave/data:/var/lib/mysql
      - ./localtime:/etc/localtime
      - ./timezone:/etc/timezone
    restart: always
    networks:
      - overlay
      
networks:
  overlay: